#!/usr/bin/env node
/**
 * Reads frontend/.env and writes public/env.js so the browser can read
 * MAPBOX_TOKEN at runtime (Parcel does not inject process.env into the client).
 * Run: node scripts/write-env.js (or npm run env)
 */
const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '..', '.env');
const outPath = path.join(__dirname, '..', 'env.js');

let token = '';
if (fs.existsSync(envPath)) {
  const content = fs.readFileSync(envPath, 'utf8');
  const match = content.match(/(?:VITE_MAPBOX_TOKEN|MAPBOX_TOKEN)\s*=\s*(\S+)/);
  if (match) token = match[1].trim();
}

const js = `// Generated by scripts/write-env.js - do not commit if it contains a secret
window.__MAPBOX_TOKEN__ = ${JSON.stringify(token)};
`;
fs.writeFileSync(outPath, js);
console.log('Wrote env.js (MAPBOX_TOKEN:', token ? 'set' : 'empty', ')');
